apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: jonathan02/backendgarden:1  # Replace with your actual image name
          ports:
            - containerPort: 8080
          env:
            - name: PGDATABASE
              value: "postgres"  # This is the database you are connecting to
            - name: PGUSER
              value: "postgres"  # The user for PostgreSQL
            - name: PGPASSWORD
              value: "postgres"
             
---

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort  # You can change to LoadBalancer or NodePort if needed for external access
