pipeline {
    agent any

    environment {
        AWS_REGION    = 'ap-south-1'
        ECR_REPO_WEB  = '836759839628.dkr.ecr.ap-south-1.amazonaws.com/prod/web'
        IMAGE_TAG     = "${gitCommit}-${BUILD_NUMBER}"
    }

    stages {
        stage('Build Docker Images') {
            parallel {
                stage('Build Web Image') {
                    steps {
                        script {
                            // Build web app image for prod
                            sh """
                                docker build -t $ECR_REPO_WEB:$IMAGE_TAG .
                            """
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Docker image built successfully.'
        }
        failure {
            echo 'Docker image build failed.'
        }
    }
}
